name: Shell Commands

on: [push, pull_request]

jobs:
     build:
        runs-on: ubuntu-latest
        strategy:
           matrix:
            node: "lts/*"
            include:
               env:
                 PACKAGE_LOCATION: Client
                 PACKAGE_LOCATION: server
          - run: cd $PACKAGE_LOCATION
        name: Node ${{ matrix.node }} sample
        steps:
          - uses: actions/checkout@v2
          - name: Setup node
            uses: actions/setup-node@v2
            with:
              node-version: ${{ matrix.node }}
          - run: npm run format
          - run: npm run lint
          - run: npm run build
          - run: npm test
